export const clientsData = [
  {
    id: 1,
    propiedades: "814",
    name: "ALEJANDRO URIBE HOSIE",
    contacto: "ADELAIDA URIBE MEJIA",
    beneficiarios: "Mauricio Uribe",
    instrucciones_de_pago: "Cta. Cte. 202193 T.O. Swiss Bank Overseas Pma.",
  },
  {
    id: 2,
    propiedades: "811",
    name: "PATRICIA URIBE DE ECHEVERRI",
    contacto: "ADELAIDA URIBE MEJIA",
    beneficiarios: "",
    instrucciones_de_pago: "Cta. Cte. 202193 T.O. Swiss Bank Overseas Pma.",
  },
  {
    id: 3,
    propiedades: "815",
    name: "ARESMO, S.A.",
    contacto: "ARMANDO ESPINOSA",
    beneficiarios: "Vellehr, S.A.",
    instrucciones_de_pago: "Llamar 261-4613 Rosa, lo viene a buscar",
  },
  {
    id: 4,
    propiedades: "417",
    name: "ARMANDO RUIZ",
    contacto: "ARMANDO RUIZ",
    beneficiarios: "Armando Ruiz Victor",
    instrucciones_de_pago: "Cheque a HSBC/SIC SHOMURA INV",
  },
  {
    id: 5,
    propiedades: "301",
    name: "ARTESANA, S.A.",
    contacto: "ARTURO SESANA",
    beneficiarios: "Artesana, S.A.",
    instrucciones_de_pago: "llamar a Silvia de Castro al Tel. 213-0574",
  },
  {
    id: 6,
    propiedades: "701",
    name: "ARTESANA, S.A.",
    contacto: "ARTURO SESANA",
    beneficiarios: "Artesana, S.A.",
    instrucciones_de_pago: "llamar a Silvia de Castro al Tel. 213-0574",
  },
  {
    id: 7,
    propiedades: "801",
    name: "ARTESANA, S.A.",
    contacto: "ARTURO SESANA",
    beneficiarios: "Artesana, S.A.",
    instrucciones_de_pago: "llamar a Silvia de Castro al Tel. 213-0574",
  },
  {
    id: 8,
    propiedades: "201",
    name: "ELECTRIC TRADING CORP.",
    contacto: "CARLOS A. ISAZA",
    beneficiarios: "Electric Trading Corp",
    instrucciones_de_pago: "Cta. Cte.11006-104-0001 Sudameris Electric Trad.",
  },
  {
    id: 9,
    propiedades: "203",
    name: "HIBIERNO MANAGEMENT",
    contacto: "CARLOS A. ISAZA",
    beneficiarios: "Tabasara International",
    instrucciones_de_pago: "Cta. Ah.10342-104-0004 - Banque Sudameris",
  },
  {
    id: 10,
    propiedades: "204",
    name: "SABOGA MANAGEMENT",
    contacto: "CARLOS A. ISAZA",
    beneficiarios: "",
    instrucciones_de_pago: "Cta. Ah.10342-104-0004 - Banque Sudameris",
  },
  {
    id: 11,
    propiedades: "803",
    name: "ULZANA INTERNACIONAL",
    contacto: "ULZANA INTERNACIONAL",
    beneficiarios: "",
    instrucciones_de_pago: "Cta. Ah.10342-104-0004 - Banque Sudameris",
  },
  {
    id: 12,
    propiedades: "809",
    name: "ENTESA",
    contacto: "ELIAS ENTEBI",
    beneficiarios: "Wytec Corporation, S.A.",
    instrucciones_de_pago: "llamar 263-9134 a Yontob- lo vienen a buscar",
  },
  {
    id: 13,
    propiedades: "805",
    name: "ERNESTO DE LA GUARDIA",
    contacto: "ERNESTO DE LA GUARDIA",
    beneficiarios: "Ernesto De La Guardia",
    instrucciones_de_pago: "llamar 264-2124 - lo viene a buscar",
  },
  {
    id: 14,
    propiedades: "715",
    name: "CELMEC, S.A.",
    contacto: "ERNESTO RICHA",
    beneficiarios: "Celmec, S.A.",
    instrucciones_de_pago: "Llamar 232-4226 - lo viene a buscar",
  },
  {
    id: 15,
    propiedades: "802",
    name: "BLUE CORAL, INC.",
    contacto: "FRANCISCO LOPEZ",
    beneficiarios: "Amparo Guzman/Francisco López",
    instrucciones_de_pago: "Cta. Ah.2424104-0001 - Banque Sudameris",
  },
  {
    id: 16,
    propiedades: "217",
    name: "PANAMA BLUE, S.A.",
    contacto: "FRANCISCO LOPEZ",
    beneficiarios: "",
    instrucciones_de_pago: "Cta. Ah.2424104-0001 - Banque Sudameris",
  },
  {
    id: 17,
    propiedades: "205",
    name: "SWISS FINANCIAL SERVICES",
    contacto: "HANS J. FINK",
    beneficiarios: "Swiss Financial Services Offshore, S.A.",
    instrucciones_de_pago: "Cta. 63-01-22408-0 Bco. Aleman Platina",
  },
  {
    id: 18,
    propiedades: "810",
    name: "SWISS FINANCIAL SERVICES",
    contacto: "HANS J. FINK",
    beneficiarios: "Swiss Financial Services Offshore, S.A.",
    instrucciones_de_pago: "Cta. 63-01-22408-0 Bco. Aleman Platina",
  },
  {
    id: 19,
    propiedades: "607",
    name: "HECTOR C. RAMIREZ",
    contacto: "HECTOR C. RAMIREZ",
    beneficiarios: "Hector Calixto Ramirez",
    instrucciones_de_pago: "Banco Nacional de Panamá- cta. 01498495",
  },
  {
    id: 20,
    propiedades: "505",
    name: "IVAN VALDERRAMA",
    contacto: "IVAN VALDERRAMA",
    beneficiarios: "Ivan Valderrama",
    instrucciones_de_pago: "Llamar 225-6709 Natalia - lo viene a buscar",
  },
  {
    id: 21,
    propiedades: "714",
    name: "JEAN PASCAL DECAILLET",
    contacto: "JEAN PASCAL DECAILLET",
    beneficiarios: "Jean Pascal Decaillet",
    instrucciones_de_pago:
      "Great Western Bank/A. Federal Savings Bank ABA 322270039 Cta. 530839812-1 Miami, Fl.",
  },
  {
    id: 22,
    propiedades: "706",
    name: "HARBOR CORPORATION",
    contacto: "JOAQUIN DE LA GUARDIA",
    beneficiarios: "Harbor Corporation",
    instrucciones_de_pago: "Correo Certificado Apdo. 236 zona 9A Panamá",
  },
  {
    id: 23,
    propiedades: "604",
    name: "JOAQUIN REVELO",
    contacto: "JOAQUIN REVELO",
    beneficiarios: "Luis Revelo",
    instrucciones_de_pago: "Cta. Ah Primax-Pba 25-15-66026-7",
  },
  {
    id: 24,
    propiedades: "601",
    name: "APRILAIR, S. A.",
    contacto: "JORGE MORGAN",
    beneficiarios: "Aprilair, S.A.",
    instrucciones_de_pago: "llamar 263-8822 Dayra - lo viene a buscar",
  },
  {
    id: 25,
    propiedades: "605",
    name: "LEYLA IBRAHIM",
    contacto: "LEYLA IBRAHIM",
    beneficiarios: "Leyla Ibrahim",
    instrucciones_de_pago: "Cta.0100686980/110153 Ocean Bank Miami, Fl.",
  },
  {
    id: 26,
    propiedades: "711",
    name: "LUIS F. MEJÍA",
    contacto: "Monica Ramirez / Cemco",
    beneficiarios: "Siena International",
    instrucciones_de_pago:
      "Transf. Bco. de Bogota Int'l.Corp. / Federal Reserve Bank- ABA066010720- Cta. 036240",
  },
  {
    id: 27,
    propiedades: "712",
    name: "LUIS F. MEJÍA",
    contacto: "LUIS F. MEJÍA",
    beneficiarios: "",
    instrucciones_de_pago:
      "Transf. Bco. de Bogota Int'l.Corp. / Federal Reserve Bank- ABA066010720- Cta. 036240",
  },
  {
    id: 28,
    propiedades: "704",
    name: "SAMDA, S. A.",
    contacto: "MA. GABRIELA ROSAS",
    beneficiarios: "Maria Gabriela Rosas M.",
    instrucciones_de_pago:
      "Helm Bank, Miami-cta. 067011456 1200Brickell Ave. Miami, Fl.33131",
  },
  {
    id: 29,
    propiedades: "716",
    name: "MAOLMA, S.A",
    contacto: "MAOLMA, S.A",
    beneficiarios: "Guillermo Ronderos Torres",
    instrucciones_de_pago: "Enviar a Oficina de WTC",
  },
  {
    id: 30,
    propiedades: "405",
    name: "LAS EMES, S.A",
    contacto: "MARIA H. ALONSO",
    beneficiarios: "Maria H Alonso",
    instrucciones_de_pago: "Cta. Cte. Pba 25-0125401-8",
  },
  {
    id: 31,
    propiedades: "603",
    name: "INMOBILIARIA LAMAR",
    contacto: "MAX FASANO",
    beneficiarios: "Inversiones Bremar, S.A.",
    instrucciones_de_pago: "Correo Certificado 0832-0903 WTC",
  },
  {
    id: 32,
    propiedades: "606",
    name: "ELMEC, S.A.",
    contacto: "NISSIM COHEN",
    beneficiarios: "Elmec, S.A.",
    instrucciones_de_pago: "llamar 229-2599 Daniel Cohen - lo viene a buscar",
  },
  {
    id: 33,
    propiedades: "617",
    name: "CAPITAN A. VALBUENA",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Alfonso Valbuena",
    instrucciones_de_pago:
      "Cta. 2685302-900506- First Union National Bank/ Miami Fl.-8201.NW 36 st. Miami Fl.33166 USA",
  },
  {
    id: 34,
    propiedades: "717",
    name: "ORLANDO FORERO",
    contacto: "ORLANDO FORERO",
    beneficiarios: "Orlando Forero",
    instrucciones_de_pago:
      "Transf. Bank of New York/British Bank of Latin America ABA 021000018 Cta. 002-902-430-4",
  },
  {
    id: 35,
    propiedades: "804",
    name: "PLAZA MANAGEMENT EQUITIES",
    contacto: "PETER BRUETSCH",
    beneficiarios: "Plaza Management Equties",
    instrucciones_de_pago: "llamar 264-4904 -P. Bruetsch - lo vienen a buscar",
  },
  {
    id: 36,
    propiedades: "710",
    name: "RAFAEL ROLDAN",
    contacto: "RAFAEL ROLDAN",
    beneficiarios: "Rafael Roldan",
    instrucciones_de_pago: "Cta. Cte. 105353-1 Bco. del Pacifico",
  },
  {
    id: 37,
    propiedades: "501",
    name: "CONASE SURAMERICANA",
    contacto: "RAUL MORRICE",
    beneficiarios: "Conase",
    instrucciones_de_pago: "Cta. Cte. Pba. 01-010070-6",
  },
  {
    id: 38,
    propiedades: "808",
    name: "RAUL ORILLAC ARANGO",
    contacto: "RAUL ORILLAC ARANGO",
    beneficiarios: "Raul Orillac Quijano",
    instrucciones_de_pago: "Cta. Cte. Pba 01-0102384-7",
  },
  {
    id: 39,
    propiedades: "401",
    name: "BALPAN, S. A.",
    contacto: "ROBERTO ROY",
    beneficiarios: "Balpan, S.A.",
    instrucciones_de_pago: "Llamar 270-0922 - lo viene a buscar",
  },
  {
    id: 40,
    propiedades: "707",
    name: "BALPAN, S. A.",
    contacto: "ROBERTO ROY",
    beneficiarios: "",
    instrucciones_de_pago: "Llamar 270-0922 - lo viene a buscar",
  },
  {
    id: 41,
    propiedades: "708",
    name: "BALPAN, S. A.",
    contacto: "ROBERTO ROY",
    beneficiarios: "",
    instrucciones_de_pago: "Llamar 270-0922 - lo viene a buscar",
  },
  {
    id: 42,
    propiedades: "709",
    name: "BALPAN, S. A.",
    contacto: "ROBERTO ROY",
    beneficiarios: "",
    instrucciones_de_pago: "Llamar 270-0922 - lo viene a buscar",
  },
  {
    id: 43,
    propiedades: "812",
    name: "MARTINO, S.A.",
    contacto: "ROBERTO ROY",
    beneficiarios: "Martino, S.A.",
    instrucciones_de_pago: "Llamar 270-0922 - lo viene a buscar",
  },
  {
    id: 44,
    propiedades: "705",
    name: "FREDERICK CHANG",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Frederick Chang",
    instrucciones_de_pago: "Avisar a W. T. C a la Lic. Chen",
  },
  {
    id: 45,
    propiedades: "806",
    name: "HSBC Bank",
    contacto: "Royal Hotel Corp",
    beneficiarios: "HSBC Bank",
    instrucciones_de_pago: "HSBC Bank",
  },
  {
    id: 46,
    propiedades: "807",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 47,
    propiedades: "L. H.",
    name: "HOTELERA MARBELLA",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Hotelera Marbella",
    instrucciones_de_pago: "Hotelera Marbella",
  },
  {
    id: 48,
    propiedades: "202",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 49,
    propiedades: "208",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 50,
    propiedades: "209",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 51,
    propiedades: "210",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 52,
    propiedades: "211",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 53,
    propiedades: "212",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 54,
    propiedades: "214",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 55,
    propiedades: "215",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 56,
    propiedades: "216",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 57,
    propiedades: "302",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 58,
    propiedades: "303",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 59,
    propiedades: "304",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 60,
    propiedades: "305",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 61,
    propiedades: "306",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 62,
    propiedades: "307",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 63,
    propiedades: "308",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 64,
    propiedades: "309",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 65,
    propiedades: "310",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 66,
    propiedades: "311",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 67,
    propiedades: "312",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 68,
    propiedades: "314",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 69,
    propiedades: "315",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 70,
    propiedades: "316",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 71,
    propiedades: "317",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 72,
    propiedades: "402",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 73,
    propiedades: "403",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 74,
    propiedades: "404",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 75,
    propiedades: "406",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 76,
    propiedades: "407",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 77,
    propiedades: "408",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 78,
    propiedades: "409",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 79,
    propiedades: "410",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 80,
    propiedades: "411",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 81,
    propiedades: "412",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 82,
    propiedades: "414",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 83,
    propiedades: "415",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 84,
    propiedades: "416",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 85,
    propiedades: "502",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 86,
    propiedades: "503",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 87,
    propiedades: "504",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 88,
    propiedades: "506",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 89,
    propiedades: "507",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 90,
    propiedades: "508",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 91,
    propiedades: "509",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 92,
    propiedades: "510",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 93,
    propiedades: "511",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 94,
    propiedades: "512",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 95,
    propiedades: "514",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 96,
    propiedades: "515",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 97,
    propiedades: "516",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 98,
    propiedades: "517",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 99,
    propiedades: "602",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 100,
    propiedades: "608",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 101,
    propiedades: "609",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 102,
    propiedades: "610",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 103,
    propiedades: "611",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 104,
    propiedades: "612",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 105,
    propiedades: "615",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 106,
    propiedades: "616",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotel Corp",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 107,
    propiedades: "816",
    name: "SISTEMAS DE PANAMA, S.A.",
    contacto: "MARY M. DE LYONS",
    beneficiarios: "Royal Hotels Corp.",
    instrucciones_de_pago:
      "Regal Group, S.A.-cta.cte. 01-002-541959 Bco.General",
  },
  {
    id: 108,
    propiedades: "817",
    name: "PRINCESS PROPERTY INVESTMENT",
    contacto: "Royal Hotels Corp.",
    beneficiarios: "Princess Property Investment Inc.",
    instrucciones_de_pago: "Princess Property Investment Inc.",
  },
  {
    id: 109,
    propiedades: "206",
    name: "RED STAR INVESTMENT",
    contacto: "URIEL J. SHAREF",
    beneficiarios: "Uriel J. Sharef",
    instrucciones_de_pago: "Enviar a Bco. Aleman Platina Sra. Myriam Figueroa",
  },
  {
    id: 110,
    propiedades: "207",
    name: "RED STAR INVESTMENT",
    contacto: "URIEL J. SHAREF",
    beneficiarios: "",
    instrucciones_de_pago: "Enviar a Bco. Aleman Platina Sra. Myriam Figueroa",
  },
  {
    id: 111,
    propiedades: "702",
    name: "INVERSIONES VILY",
    contacto: "VICTOR SHAHANI",
    beneficiarios: "Amirab Investment, S.A.",
    instrucciones_de_pago: "Llamar 220-6173 Arq. Altuna -vienen a buscarlo",
  },
  {
    id: 112,
    propiedades: "703",
    name: "INVERSIONES VILY",
    contacto: "VICTOR SHAHANI",
    beneficiarios: "",
    instrucciones_de_pago: "Llamar 220-6173 Arq. Altuna -vienen a buscarlo",
  },
  {
    id: 113,
    propiedades: "0",
    name: "QUVAN, S.A.",
    contacto: "VILMA PINILLA",
    beneficiarios: "Vilma Pinilla",
    instrucciones_de_pago:
      "Cta. 1050141633- Helm Bank 1312 South Miami Ave.Miami, Fl. 33130",
  },
];
